version: 0.2

env:
  variables:
    WAMBDA_DEBUG: "true"
    WAMBDA_USE_MOCK: "false"
    WAMBDA_NO_AUTH: "false"
    WAMBDA_DENY_SIGNUP: "false"
    WAMBDA_DENY_LOGIN: "false"
    WAMBDA_LOG_LEVEL: "DEBUG"
    S3_BUCKET: "wambda-csr001-main"
    DYNAMODB_TABLE: "wambda-table-csr001"

phases:
  install:
    runtime-versions:
      python: 3.13
      nodejs: 20
  pre_build:
    commands:
      # Check if triggered by GitHub webhook
      - |
        if [[ "$CODEBUILD_INITIATOR" == *"GitHub-Hookshot"* ]]; then
          echo "Triggered by GitHub webhook - checking for changes"
          WEBHOOK_TRIGGER=true

          # Check if HEAD~1 exists (not initial commit)
          if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
            echo "Checking changes since previous commit"

            # Check for Backend changes
            if git diff --name-only HEAD~1 HEAD | grep -q "^Backend/"; then
              echo "Backend changes detected"
              DEPLOY_BACKEND=true
            else
              echo "No Backend changes detected"
              DEPLOY_BACKEND=false
            fi

            # Check for Frontend changes
            if git diff --name-only HEAD~1 HEAD | grep -q "^Frontend/"; then
              echo "Frontend changes detected"
              DEPLOY_FRONTEND=true
            else
              echo "No Frontend changes detected"
              DEPLOY_FRONTEND=false
            fi
          else
            echo "Initial commit or HEAD~1 not available - deploying both"
            DEPLOY_BACKEND=true
            DEPLOY_FRONTEND=true
          fi
        else
          echo "Not triggered by GitHub webhook - deploying both Backend and Frontend"
          WEBHOOK_TRIGGER=false
          DEPLOY_BACKEND=true
          DEPLOY_FRONTEND=true
        fi
      # Install Frontend dependencies if Frontend directory exists
      - |
        if [[ -d "Frontend" ]]; then
          echo "Installing Frontend dependencies"
          cd Frontend && npm ci && cd ..
        else
          echo "Frontend directory not found - skipping npm install"
        fi
  build:
    commands:
      # Deploy Backend if needed
      - |
        if [[ "$DEPLOY_BACKEND" == "true" ]]; then
          cd Backend
          echo "Building and deploying Backend..."
          sam build
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides ParameterKey=DEBUG,ParameterValue=$WAMBDA_DEBUG ParameterKey=UseMock,ParameterValue=$WAMBDA_USE_MOCK ParameterKey=NoAuth,ParameterValue=$WAMBDA_NO_AUTH ParameterKey=DenySignup,ParameterValue=$WAMBDA_DENY_SIGNUP ParameterKey=DenyLogin,ParameterValue=$WAMBDA_DENY_LOGIN ParameterKey=LogLevel,ParameterValue=$WAMBDA_LOG_LEVEL ParameterKey=DynamoDBTable,ParameterValue=$DYNAMODB_TABLE
          cd ..
        else
          echo "Skipping Backend deployment"
        fi
      # Deploy Frontend if needed
      - |
        if [[ "$DEPLOY_FRONTEND" == "true" ]] && [[ -d "Frontend" ]]; then
          echo "Building and deploying Frontend..."
          # cd Frontend
          # npm run build
          # aws s3 sync dist/ s3://$S3_BUCKET/CloudFront/app --delete
          # cd ..
        else
          echo "Skipping Frontend deployment (not needed or Frontend directory not found)"
        fi